---
services:
  bot:
    container_name: esgi-bot
    restart: unless-stopped
    image: esgi-discord-bot:${BOT_VERSION}
    build:
      context: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./volumes/imports:/tmp/imports
...
