---
services:
  bot:
    container_name: esgi-bot
    restart: unless-stopped
    image: esgi-discord-bot:${BOT_VERSION}
    build:
      context: .
    env_file: .env
    volumes:
      - ./volumes/imports:${IMPORTS_PATH}
      - ./volumes/db:${DATABASE_PATH}
...
