---
name: 'Hadolint'
on:  # yamllint disable-line rule:truthy
  - pull_request
  - push
jobs:
  hadolint:
    name: 'Hadolint'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Hadolint'
        uses: jbergstroem/hadolint-gh-action@v1
...
